### ISSUE TITLE
where are the weights?

### ISSUE THREAD

**Issue by bochen2027** [unrealgo/unrealgo#1]
any 40 block s

**Comment by unrealgo** [comment]
A compressed bootstrap weights bootstrap.tar.gz is located at the root of project.

**Comment by bochen2027** [comment]
So some feedback if you don't mind, given that there are already two other alphagozero duplicates out there (MiniGo, LeelaZero) and the fact that it is so resource extensive to train a strong network (minigo has access to 1000 TPU from Google while LeelaZero has hundreds of client volunteers) I'm curious what would be the differientator for something like UnrealGo to start from scratch? 

Wouldn't it be more effective to try something novel or new, like say code it for BOINC (LeelaZero isn't on BOINC and neither is Minigo)  and try the blockchain and cryptocurrency approach (afaik no Go project has a blockchain or use cryptocurrency to reward contributors or cycles of computing) to attempt to attract more mindshare and crowd share? 

While minigo is still lagging behind, at this point LeelaZero has already reached pro level and would take at least six months for any similiar project to catch up (assuming such were even possible) if starting from zero. Unless something catastrophic happens with the LeelaZero project and/or your UnrealGo project finds some new breakthrough or whatever, it doesn't seem like its realistic that UnrealGo can catch up in strength. And if it isn't about strength, then what is it about? Since the success of LeelaZero has already proven the AlphagoZero method works and their paper is valid. 

Have you thought outside the box and other ways to approach this? Having a third option (LeelaZero, MiniGo and now UnrealGo) is always good, but it should take advantage of where the other two are lacking. 

Maybe UnrealGo can be the 40 block 256 filter size that LeelaZero doesn't want to do/be/become. It can bootstrap all the preexisting LeelaZero raw training game data into a net2net 40 block 256 filter and just go from there, join BOINC and start its own blockchain and Go cryptocurrency to encourage as much volunteer clients to donate GPU resources as possible and it can be the contender to fill the 40block niche that no one else wants to try. It seems to me this is a much more reasonable approach at this late in the game and the only way UnrealGo has any hopes of quickly catching up to LeelaZero.

**Comment by unrealgo** [comment]
So far as I know there is no good idea to use neural network as a POW for blockchain.
